name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v1.2.3
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore UniqueArtGenerate/UniqueArtGenerate.csproj

    - name: Publish Native AOT
      run: dotnet publish UniqueArtGenerate/UniqueArtGenerate.csproj -c Release -r win-x64 --self-contained -o ./publish

    - name: Rename artifact
      run: Rename-Item -Path ./publish/UniqueArtGenerate.exe -NewName UniqueArtGenerate-win-x64.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: UniqueArtGenerate-win-x64
        path: ./publish/UniqueArtGenerate-win-x64.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: UniqueArtGenerate-win-x64
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/UniqueArtGenerate-win-x64.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
